# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CraftyMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CraftyMe

pod 'Firebase/Auth' 
pod 'Firebase/Database'
pod 'Firebase/Storage'

# Image download async
pod 'SDWebImage'

pod 'IQKeyboardManager'
pod 'IQDropDownTextField'

pod 'SwiftMessages', '~> 5.0'
pod 'SVProgressHUD'
pod 'ObjectMapper'

end
